# fly.toml app configuration file generated for maria-db-mcp-datastore on 2026-09-13T19:17:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'maria-db-mcp-datastore'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[restart]]
  policy = 'always'
  processes = ['app']
  retries = 10
